# Generated by Django 2.0 on 2020-04-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200401_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, height_field='picture_height', max_length=255, null=True, upload_to='profile_pictures/%Y/%m/%d/', width_field='picture_width'),
        ),
    ]
