# Generated by Django 2.0 on 2020-04-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20200401_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_at',)},
        ),
    ]
